# Generated by Django 4.2.1 on 2023-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=1, max_length=12, unique=True, verbose_name='Number phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
